theme: jekyll-theme-midnight
title: "Viola: Trustworthy Sensor Notifications for Enhanced Privacy on Mobile Systems"
name: "Viola: Trustworthy Sensor Notifications for Enhanced Privacy on Mobile Systems"
show_downloads: true
